### ISSUE TITLE
README文件编码问题

### ISSUE THREAD

**Issue by dalaomai** [MidTin/rabbit-rpc#1]
`  Cloning https://github.com/MidTin/rabbit-rpc.git (to master) to c:\users\xxx\appdata\local\temp\pip-build-1z_zx9_k\rabbit-rpc
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-build-1z_zx9_k\rabbit-rpc\setup.py", line 14, in <module>
        README = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode bxxyte 0x80 in position 41: illegal multibyte sequence`

**Comment by dalaomai** [comment]
read()加上参数encoding='utf-8'
